# Generated by Django 3.0.3 on 2020-02-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('regist_date', models.DateField(auto_now_add=True, verbose_name='注册日期')),
            ],
        ),
        migrations.CreateModel(
            name='Artice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('sumire', models.CharField(max_length=100, verbose_name='正文')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='图书名')),
                ('price', models.FloatField(default=0, verbose_name='图书价格')),
                ('bpub_date', models.DateField(default='1983-06-01')),
                ('desc', models.CharField(blank=True, help_text='请输入图书的备注信息', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
            ],
            options={
                'verbose_name': '用户模型表1',
                'verbose_name_plural': '用户模型表2',
                'db_table': '用户表',
                'ordering': ['telephone'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30, verbose_name='标签名')),
                ('artices', models.ManyToManyField(related_name='tags', to='booktest.Artice')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6)),
                ('content', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='booktest.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Concact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('email', models.EmailField(default='2861358163@qq.com', max_length=254)),
                ('accont', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booktest.Accont')),
            ],
        ),
    ]
