# Generated by Django 3.0.3 on 2020-02-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(blank=True, help_text='请输入图书的备注信息', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=25, unique=True, verbose_name='图书名'),
        ),
    ]
