# Generated by Django 3.0.3 on 2020-02-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_auto_20200215_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('sumire', models.CharField(max_length=100, verbose_name='正文')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30, verbose_name='标签名')),
            ],
        ),
    ]
