# Generated by Django 3.0.3 on 2020-02-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0007_artice_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='artices',
            field=models.ManyToManyField(to='booktest.Artice'),
        ),
    ]
