# Generated by Django 3.0.3 on 2020-02-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='轮播图片')),
                ('desc', models.CharField(max_length=20, verbose_name='活动描述')),
            ],
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('price', models.FloatField(default=0.0, verbose_name='商品价格')),
                ('img', models.ImageField(upload_to='good_img', verbose_name='商品图片')),
                ('desc', models.CharField(max_length=100, verbose_name='商品描述')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.GoodCategory', verbose_name='商品分类')),
            ],
        ),
    ]
